
# Defines both containers (app + database) needed to run this project,
# so instead of separate "docker build" + "docker run" commands for each,
# we start everything together with a single "docker compose up".

services:
    db:
      image: postgres:16
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: "nada"
        POSTGRES_PASSWORD : "devpassword"
        POSTGRES_DB : "logs_db"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U nada -d logs_db"]
        interval: 5s
        timeout: 5s
        retries: 5
      deploy:
        resources:
          limits:
            cpus: "1.0"
            memory: 1GB

    app:
      build: .
      ports: 
        - "8080:8080"
      environment:
        DATABASE_URL : "postgres://nada:devpassword@db:5432/logs_db"
        RETENTION_DAYS : 30

      deploy:
        resources:
          limits:
            cpus: "0.5"
            memory: 256M
      depends_on:
        db:
          condition: service_healthy
      
    