
# Defines both containers (app + database) needed to run this project,
# so instead of separate "docker build" + "docker run" commands for each,
# we start everything together with a single "docker compose up".

services:
    app:
      build: .
      ports: 
        - "8080:8080"
      env_file:
        - .env
      deploy:
        resources:
          limits:
            cpus: "0.5"
            memory: 256M
    
    db:
      image: postgres:16
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: "nada"
        POSTGRES_PASSWORD : ${DB_PASSWORD}
        POSTGRES_DB : "logs_db"
      deploy:
        resources:
          limits:
            cpus: "1"
            memory: 1GB
